# Site settings
title: Microsoft PowerToys Offline Setup Assistant
email: contact@microsoft-tools.github.io
description: >- # this means to ignore newlines until "baseurl:"
  The official documentation for the PowerToys Offline Setup Assistant.
  Learn how to install, configure, and troubleshoot PowerToys in offline and enterprise environments.
baseurl: "/microsoftpowertoys" # the subpath of your site, e.g. /blog
url: "https://microsoft-tools.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Microsoft
github_username:  Microsoft-Tools

# Build settings
markdown: kramdown
theme: "just-the-docs"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings
color_scheme: dark
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default true
  heading_level: 2
  # Maximum number of previews per search result
  # Default: 3
  previews: 5
  # Maximum number of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum number of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set to true to return nil when there are no search results
  # Default: false
  empty_search_results: false
  # Manual ordering of search results
  # The order is determined by the order of existing files
  # Supports true, false, 'reversed'
  # Default: false
  sort_order: false
  # When true, display closest match search result text underneath the search result title
  # Default: true
  preview_type: 'text'

# SEO Tag settings
logo: /assets/images/logo.png
social:
  name: Microsoft PowerToys Assistant
  links:
    - https://twitter.com/Microsoft
    - https://github.com/Microsoft-Tools/microsoftpowertoys

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/ 